server:
  port: 8799
spring:
  application:
    name: eurekaclient
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
spring:
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: cctest
        password: 123456
        virtualHost: /
        publisherConfirms: true
